<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SuperHeroes.DAL\SuperHeroes.DAL.csproj" />
    <ProjectReference Include="..\SuperHeroes.Entities\SuperHeroes.Entities.csproj" />
  </ItemGroup>

</Project>
